version: "3"

services:
    bankuish:
      build: 
        context: ./
      restart: unless-stopped
      ports:
        - 4000:4000
     
    db:
      image: mysql
      restart: always
      environment:
      MYSQL_DATABASE: 'schedule_courses'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ismael'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      
   
